#!/bin/bash

#SBATCH --job-name=cla_embedding_dimension
#SBATCH --output=cla_embedding_dimension_output.txt
#SBATCH --error=cla_embedding_dimension_error.txt
#SBATCH --time=03:00:00
#SBATCH --qos=cs
#SBATCH --nodes=1
#SBATCH --ntasks=100
#SBATCH --gpus=2
#SBATCH --mem=500G
#SBATCH --mail-user=yws226@byu.edu
#SBATCH --mail-type=BEGIN,END,FAIL

# Load modules or activate environment
module load python/3.8.18
mamba activate dnnenv

# Run the meta-study for embedding_dimension
python cla.py --study 'embedding_dimension' --output_dir 'meta_study_results/embedding_dimension'
